spring.application.name=backend

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Admin
admin.email=your_admin_email@example.com
admin.password=your_admin_password

# JWT
jwt.secret=${JJWT_SECRET:your_jwt_secret}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Cloudinary
cloudinary.cloud.name=your_cloud_name
cloudinary.api.key=your_cloudinary_api_key
cloudinary.api.secret=your_cloudinary_api_secret

# Database Driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Brevo
brevo.api.key=your_brevo_api_key
mail.sender=your_email@example.com